spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tianyadu
    password: Qq893214347!
    url: jdbc:mysql://47.95.6.60:3306/spring_cloud_sell?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  rabbitmq:
    host: 47.95.6.60
    port: 5672
    username: guest
    password: guest
  redis:
    host: 47.95.6.60
    port: 16381
  jpa:
    show-sql: true
girl: 18